/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as _01DataTypesSol from './01_data_types.sol/index.js';
export * as _02FunctionsSol from './02_functions.sol/index.js';
export * as _03VisibilitySol from './03_visibility.sol/index.js';
export * as _04ModifiersSol from './04_modifiers.sol/index.js';
export * as _05PayableSol from './05_payable.sol/index.js';
export * as _06ConstructorSol from './06_constructor.sol/index.js';
export * as arraysSol from './arrays.sol/index.js';
export * as conditionalsSol from './conditionals.sol/index.js';
export * as erorrsSol from './erorrs.sol/index.js';
export * as etherSol from './ether.sol/index.js';
export * as eventSol from './event.sol/index.js';
export * as globalVariableSol from './global_variable.sol/index.js';
export * as inheritanceSol from './inheritance.sol/index.js';
export * as interactionSol from './interaction.sol/index.js';
export * as interfacesSol from './interfaces.sol/index.js';
export * as mapSol from './map.sol/index.js';
export * as mycontractSol from './mycontract.sol/index.js';
export * as operatorSol from './operator.sol/index.js';
export * as structSol from './struct.sol/index.js';