/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface GreetingInterface extends Interface {
    getFunction(nameOrSignature: "changeCount" | "getMessage" | "isOwner" | "message" | "owner" | "setMessage"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "MessageChanged"): EventFragment;

    encodeFunctionData(functionFragment: 'changeCount', values?: undefined): string;
encodeFunctionData(functionFragment: 'getMessage', values?: undefined): string;
encodeFunctionData(functionFragment: 'isOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'message', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'setMessage', values: [string]): string;

    decodeFunctionResult(functionFragment: 'changeCount', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMessage', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'message', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setMessage', data: BytesLike): Result;
  }

  
    export namespace MessageChangedEvent {
      export type InputTuple = [newMessage: string, changedBy: AddressLike];
      export type OutputTuple = [newMessage: string, changedBy: string];
      export interface OutputObject {newMessage: string, changedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Greeting extends BaseContract {
    
    connect(runner?: ContractRunner | null): Greeting;
    waitForDeployment(): Promise<this>;

    interface: GreetingInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    changeCount: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    getMessage: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isOwner: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    message: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setMessage: TypedContractMethod<
      [newMessage: string, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'changeCount'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMessage'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isOwner'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'message'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setMessage'): TypedContractMethod<
      [newMessage: string, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'MessageChanged'): TypedContractEvent<MessageChangedEvent.InputTuple, MessageChangedEvent.OutputTuple, MessageChangedEvent.OutputObject>;

    filters: {
      
      'MessageChanged(string,address)': TypedContractEvent<MessageChangedEvent.InputTuple, MessageChangedEvent.OutputTuple, MessageChangedEvent.OutputObject>;
      MessageChanged: TypedContractEvent<MessageChangedEvent.InputTuple, MessageChangedEvent.OutputTuple, MessageChangedEvent.OutputObject>;
    
    };
  }