/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'DataTypes', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.DataTypes__factory>
getContractFactory(name: 'Functions', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Functions__factory>
getContractFactory(name: 'Visibility', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Visibility__factory>
getContractFactory(name: 'Modifiers', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Modifiers__factory>
getContractFactory(name: 'Payable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Payable__factory>
getContractFactory(name: 'Constructor', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Constructor__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'Ownable', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Ownable__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'SecretVault', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.SecretVault__factory>
getContractFactory(name: 'IERC20', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IERC20__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>
getContractFactory(name: 'MyContract', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MyContract__factory>

  getContractAt(name: 'DataTypes', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.DataTypes>
getContractAt(name: 'Functions', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Functions>
getContractAt(name: 'Visibility', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Visibility>
getContractAt(name: 'Modifiers', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Modifiers>
getContractAt(name: 'Payable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Payable>
getContractAt(name: 'Constructor', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Constructor>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'Ownable', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Ownable>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'SecretVault', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.SecretVault>
getContractAt(name: 'IERC20', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IERC20>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>
getContractAt(name: 'MyContract', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MyContract>

  deployContract(name: 'DataTypes', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DataTypes>
deployContract(name: 'Functions', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Functions>
deployContract(name: 'Visibility', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Visibility>
deployContract(name: 'Modifiers', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Modifiers>
deployContract(name: 'Payable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Payable>
deployContract(name: 'Constructor', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Constructor>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'Ownable', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'SecretVault', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SecretVault>
deployContract(name: 'IERC20', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>

  deployContract(name: 'DataTypes', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.DataTypes>
deployContract(name: 'Functions', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Functions>
deployContract(name: 'Visibility', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Visibility>
deployContract(name: 'Modifiers', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Modifiers>
deployContract(name: 'Payable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Payable>
deployContract(name: 'Constructor', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Constructor>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'Ownable', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Ownable>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'SecretVault', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.SecretVault>
deployContract(name: 'IERC20', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IERC20>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>
deployContract(name: 'MyContract', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MyContract>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  